# 项目信息配置
miniuri:
  info:
    version: 1.0.0
    base-package: com.zjz.mini.uri.run
  cache:
    timeout: 1

# 启动端口
server:
  port: 8888
  host: ${env.server.host:https://miniuri.com/}
  # 启用响应压缩（减少 HTML/CSS/JS/JSON 等体积）
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types: application/json,application/javascript,text/css,text/html,text/plain,application/xml,application/xhtml+xml,image/svg+xml
  # 如运行环境支持，启用 HTTP/2（浏览器访问可提升并发与头压缩效率）
  http2:
    enabled: true
  # 让服务器层处理 Forwarded / X-Forwarded-* 头，正确识别外部 scheme/host/port
  forward-headers-strategy: native

spring:
  threads:
    virtual:
      enabled: true  # 启用虚拟线程
  application:
    name: mini-uri
  web:
    resources:
      static-locations: classpath:/static/
      # 为静态资源开启强缓存 + 内容指纹（版本策略）
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /static/**
  mvc:
    static-path-pattern: /static/**
    # 让 Spring 自动解析 X-Forwarded-* / Forwarded 头，重写请求的 scheme/host/port
    # 这样 request.getScheme()/getServerName() 等可反映外部地址
    # forward-headers-strategy: native  # 移到 server.forward-headers-strategy
  thymeleaf:
    encoding: utf-8
    mode: HTML

--- # redis
spring:
  data:
    redis:
      host: ${env.redis.host}
      timeout: 10s
      username: ${env.redis.username}
      password: ${env.redis.password}
      database: 0
      port: 6379
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 10
          max-wait: 10s


--- # mysql
spring:
  datasource:
    # 主库数据源
    driverClassName: com.mysql.cj.jdbc.Driver
    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
    url: ${env.mysql.url}
    username: ${env.mysql.username}
    password: ${env.mysql.password}
    
    # HikariCP 连接池配置（Spring Boot 默认连接池）
    hikari:
      # 连接池名称
      pool-name: HikariCP-MiniUri
      # 最小空闲连接数
      minimum-idle: 10
      # 最大连接池大小
      maximum-pool-size: 50
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大存活时间（毫秒）
      max-lifetime: 1800000
      # 连接测试查询
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: true
      # 连接泄漏检测阈值（毫秒）
      leak-detection-threshold: 60000

# MyBatis Plus 的配置项
mybatis-plus:
  lazy-initialization: true # 设置 MyBatis Mapper 延迟加载
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志

