# 项目信息配置
miniuri:
  info:
    version: 1.0.0
    base-package: com.zjz.mini.uri.run
  cache:
    timeout: 1

# 启动端口
server:
  port: 8888
  host: ${env.server.host:https://miniuri.com/}

spring:
  application:
    name: mini-uri
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    encoding: utf-8
    mode: HTML

--- # redis
spring:
  data:
    redis:
      host: ${env.redis.host}
      timeout: 10s
      password:
      database: 0
      port: 6379
      ssl:
        enabled: false

--- # mysql
spring:
  datasource:
    # 主库数据源
    driverClassName: com.mysql.cj.jdbc.Driver
    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
    url: ${env.mysql.url}
    username: ${env.mysql.username}
    password: ${env.mysql.password}

# MyBatis Plus 的配置项
mybatis-plus:
  lazy-initialization: true # 设置 MyBatis Mapper 延迟加载
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志

